name: "Godot Export"

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.2
  EXPORT_NAME: TryGodot

jobs:
  godot-ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::Godot Version ${GODOT_VERSION}"
    outputs:
      version: ${{ env.GODOT_VERSION }}

  exports:
    name: Export Game
    needs:
      - godot-ci
    strategy:
      matrix:
        platform:
          - name: Windows
            preset: Windows Desktop
            path: build/windows
            executable: TryGodot.exe
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:${{ needs.godot-ci.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          cp -r /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: ${{ matrix.platform.name }} Build
        run: |
          mkdir -v -p ${{ matrix.platform.path }}
          godot -v --headless --export-release "${{ matrix.platform.preset }}" ./${{ matrix.platform.path }}/${{ matrix.platform.executable }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.name }}
          path: ${{ matrix.platform.path }}
