name: "Godot Export"

on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.2
  EXPORT_NAME: TryGodot

jobs:
  godot-ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::debug::Godot Version ${GODOT_VERSION}"
    outputs:
      version: ${{ env.GODOT_VERSION }}

  export-windows:
    name: Windows Export
    needs:
      - godot-ci
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:${{ needs.godot-ci.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          cp -r /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --headless --export-release "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: build/windows
